sonar.projectKey=TruVideoCapacitorCameraSdk
sonar.projectName=TruVideoCapacitorCameraSdk
sonar.projectVersion=1.0

# Token you created earlier
sonar.login=sqp_abf0d3b566b4a88304304b8333de222d04f7d4a9

# Source code folder
sonar.sources=src

# Ignore build files + Capacitor native folders
sonar.exclusions=**/node_modules/**, **/build/**, **/dist/**, android/**, ios/**

# Optional - for React test coverage (if using Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
